function [car_cell] = parameters_loop(mass,driver_weight,accel_driver_weight,wheelbase,weight_dist,...
    track_width,wheel_radius,cg_height,roll_center_height_front,roll_center_height_rear,R_sf,I_zz,...
    cda,cla,distribution,redline,shift_point,gears,torque_fn,final_drive,drivetrain_efficiency,G_d1,G_d2_overrun,...
    G_d2_driving,brake_distribution,max_braking_torque,gamma,p_i,Fx_parameters,Fy_parameters)

% more elegant solution to loop through parameters (in comparison to nested
%   for loops)
% output car_cell: a cell containing a car for each possible combination of
%   parameters

[mass,driver_weight,accel_driver_weight,wheelbase,weight_dist,track_width,wheel_radius,cg_height,...
    roll_center_height_front,roll_center_height_rear,R_sf,I_zz,cda,cla,distribution,redline,shift_point,...
    final_drive,drivetrain_efficiency,G_d1,G_d2_overrun,G_d2_driving,brake_distribution,max_braking_torque,gamma,p_i]...
    = ndgrid(mass,driver_weight,accel_driver_weight,wheelbase,weight_dist,track_width,wheel_radius,cg_height,...
    roll_center_height_front,roll_center_height_rear,R_sf,I_zz,cda,cla,distribution,redline,shift_point,...
    final_drive,drivetrain_efficiency,G_d1,G_d2_overrun,G_d2_driving,brake_distribution,max_braking_torque,gamma,p_i);

counter = 1;
for i = 1:numel(mass)
    aero = Aero(cda(i),cla(i),distribution(i));

    powertrain = Powertrain(redline(i),shift_point(i),gears,torque_fn,final_drive(i),wheel_radius(i),drivetrain_efficiency(i),...
                G_d1(i),G_d2_overrun(i),G_d2_driving(i),brake_distribution(i),max_braking_torque(i));
    tire = Tire2(gamma(i),p_i(i),Fx_parameters,Fy_parameters); 
    car = Car(mass(i)+driver_weight(i),wheelbase(i),weight_dist(i),track_width(i),wheel_radius(i),...
        cg_height(i),roll_center_height_front(i),roll_center_height_rear(i),R_sf(i),I_zz(i),aero,...
        powertrain,tire); 
    accel_car = Car(mass(i)+accel_driver_weight(i),wheelbase(i),weight_dist(i),track_width(i),...
        wheel_radius(i),cg_height(i),roll_center_height_front(i),roll_center_height_rear(i),R_sf(i),...
        I_zz(i),aero,powertrain,tire); 
    car_cell{i,1} = car;
    car_cell{i,2} = accel_car;
    counter = counter+1;
end
