function opts = setOptimoptions()
% opts = optimoptions('fmincon','MaxFunctionEvaluations',1000,'ConstraintTolerance',1e-2,...
%     'StepTolerance',1e-10,'Display','notify-detailed');
opts = optimoptions('fmincon','MaxFunctionEvaluations',1000,'ConstraintTolerance',1e-2,...
    'StepTolerance',1e-10,'Display','off');